server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/baissy/ConfigTensquare.git
          username: baissm@qq.com
          password: huhu0486047079
