server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.147.106:3306/tensquare_friend?useUnicode=true&amp;characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: baissy
