server:
  port: 9002
spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.37.135.119:3306/tensquare_recruit?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true

