server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 111.229.147.106
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
