server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.37.135.119:3306/tensquare_gathering?useUnicode=true&amp;characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
